// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $posts_title_ from "./routes/posts/[...title].tsx";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $LastUpdated from "./islands/LastUpdated.tsx";
import * as $ThemeButton from "./islands/ThemeButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
    "./routes/posts/[...title].tsx": $posts_title_,
    "./routes/posts/index.tsx": $posts_index,
  },
  islands: {
    "./islands/LastUpdated.tsx": $LastUpdated,
    "./islands/ThemeButton.tsx": $ThemeButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
